Fix php-fpm logging

diff --git a/php-7.1/Dockerfile b/php-7.1/Dockerfile
--- a/php-7.1/Dockerfile
+++ b/php-7.1/Dockerfile
@@ -17,17 +17,43 @@ RUN set -ex \
     && rm -rf /var/lib/apt/lists/* \
     && sh /usr/local/build-scripts/cleanup.sh
 
-RUN exec >&2 \
-    && echo "sendmail_path=/usr/sbin/ssmtp -t" | tee -a /usr/local/etc/php/conf.d/zz-01-defaults.ini \
-    && echo "apc.serializer=igbinary" | tee -a /usr/local/etc/php/conf.d/zz-01-defaults.ini \
-    && echo "session.serialize_handler=igbinary" | tee -a /usr/local/etc/php/conf.d/zz-01-defaults.ini
+ENV DOCKERIZE_VERSION=0.6.1
+RUN set -ex \
+    # install dockerize and wrap php-fpm to start with dockerize tailing /var/log/stderr and /var/log/stdout
+    && curl -L https://github.com/jwilder/dockerize/releases/download/v$DOCKERIZE_VERSION/dockerize-linux-amd64-v$DOCKERIZE_VERSION.tar.gz -o dockerize-linux-amd64-v$DOCKERIZE_VERSION.tar.gz \
+    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v$DOCKERIZE_VERSION.tar.gz \
+    && rm dockerize-linux-amd64-v$DOCKERIZE_VERSION.tar.gz \
+    && mkfifo /var/log/stderr \
+    && mkfifo /var/log/stdout \
+    && chown www-data:www-data /var/log/stdout \
+    && chown www-data:www-data /var/log/stderr \
+    && mv /usr/local/sbin/php-fpm /usr/local/sbin/php-fpm.orig \
+    && { \
+        echo '#!/bin/sh'; \
+        echo 'exec dockerize -stderr /var/log/stderr -stdout /var/log/stdout -poll /usr/local/sbin/php-fpm.orig -d"error_log=/var/log/stderr" -d"opcache.error_log=/var/log/stderr" -d"log_errors=on" -d"display_errors=off" "$@"'; \
+        } | tee /usr/local/sbin/php-fpm >/dev/null \
+    && chmod +x /usr/local/sbin/php-fpm \
+    && { \
+        echo '[global]'; \
+        echo 'error_log = /var/log/stderr'; \
+        echo; \
+        echo '[www]'; \
+        echo 'catch_workers_output = yes'; \
+        echo 'access.log = /var/log/stdout'; \
+        } | tee /usr/local/etc/php-fpm.d/zz-dockerized.conf >/dev/null
+
+RUN { \
+        echo 'sendmail_path=/usr/sbin/ssmtp -t'; \
+        echo 'apc.serializer=igbinary'; \
+        echo 'session.serialize_handler=igbinary'; \
+    } | tee /usr/local/etc/php/conf.d/zz-01-defaults.ini >&2 \
+    && { \
+       echo "<?php phpinfo(); "; \
+    } | tee /var/www/html/index.php >&2 \
+    && chown -R www-data:www-data /var/www/html
 
 COPY docker-php-entrypoint /usr/local/bin/docker-php-entrypoint
 
-RUN echo "<?php phpinfo(); " > /var/www/html/index.php
-
-EXPOSE 3000
-
+EXPOSE 9000
 ENTRYPOINT ["/usr/local/bin/docker-php-entrypoint"]
-
-CMD ["php", "-S", "0.0.0.0:3000", "-t", "/var/www/html"]
+CMD ["php-fpm"]
